# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: '.patch'
      - id: end-of-file-fixer
        exclude: '.patch'
      - id: mixed-line-ending
        exclude: ".patch"

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          [
            "--no-warnings",
            "--config-data",
            "{extends: default, rules: {line-length: disable, braces: {max-spaces-inside: 1}}}",
          ]
        types: [text]
        files: \.(yml|yaml)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v20.1.7'
    hooks:
      - id: clang-format
        args: ['-fallback-style=none', '-i']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
